task default: :test

ENV['PATH'] = "#{File.expand_path('../bin', __dir__)}:#{ENV['PATH']}"

# really, just made this to document how to run the tests
desc 'Run tests'
task :test do
  sh 'haxe compile.hxml'
  sh 'neko runtests.n'
end
